# Generated by Django 4.0.1 on 2022-01-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('origin_prize', models.DecimalField(decimal_places=3, max_digits=6)),
                ('second_prize', models.DecimalField(decimal_places=3, max_digits=6)),
                ('product_prize', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seria', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('debt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.DecimalField(decimal_places=3, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesa', to='myapp.product')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile')),
            ],
        ),
    ]
