# Generated by Django 3.2.9 on 2022-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=type, choices=[('День', 'День'), ('Час', 'Час')], default='День', max_length=200),
        ),
    ]
