# Generated by Django 3.2.9 on 2022-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220109_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='income_id',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
