# Generated by Django 3.2.9 on 2022-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220110_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='term',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_profile_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_profile_id',
            field=models.ManyToManyField(to='myapp.User_Profile'),
        ),
    ]
