# Generated by Django 3.2.9 on 2022-01-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220110_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='lesa', to='myapp.Product'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_profile_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile'),
        ),
    ]
