# Generated by Django 3.2.9 on 2022-01-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment_type_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesa', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.type_of_payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile'),
        ),
    ]
