# Generated by Django 3.2.9 on 2022-01-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220113_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='income',
            name='weight',
        ),
        migrations.AlterField(
            model_name='income',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='myapp.product'),
        ),
    ]
